### ISSUE TITLE
Prometheus-api-client incompatible with pandas version 0.23

### ISSUE THREAD

**Issue by suppathak** [AICoE/prometheus-api-client-python#126] opened 2020-06-24 18:45 UTC
**Describe the bug**
Importing metric snapshot data frame fails when pandas version is 0.23.0. 

**Error Output**
ModuleNotFoundError: No module named 'pandas._typing'

**Comment by 4n4nd** [comment] 2020-06-24 18:50
Could you please paste the error output here?

**Comment by suppathak** [comment] 2020-06-24 19:10
> Could you please paste the error output here?

Bug error updated in the description! Thank you :)

**Comment by chauhankaranraj** [comment] 2020-06-30 16:11
IIUC the root cause of this issue is that the `pandas._typing` module didn't exist in `0.23.x`. Rn I can think of three possible ways to fix this:
1. Update the `Pipfile` to have `pandas = ">=1.0.0"`
2. Remove declaring types in the `__init__` function (lines [52](https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/metric_snapshot_df.py#L52)-[56](https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/metric_snapshot_df.py#L56))
3. Mirror the update in pandas that defines the `Dtype` and `Axes` types. i.e. replace this line:
```
from pandas._typing import Axes, Dtype
```
with this:
```
from typing import Collection
from pandas.core.dtypes.dtypes import ExtensionDtype
Axes = Collection
Dtype = Union[str, np.dtype, "ExtensionDtype"]
```
Although, this method would break if pandas version was less than 0.20 (`pandas.core.dtypes.dtypes` didn't exist pre - 0.20)

WDYT? @4n4nd

**Comment by 4n4nd** [comment] 2020-07-01 14:01
@chauhankaranraj @suppathak 
>1. Update the Pipfile to have pandas = ">=1.0.0"

the first suggested solution looks the simplest to me

**Comment by suppathak** [comment] 2020-07-01 18:04
> IIUC the root cause of this issue is that the `pandas._typing` module didn't exist in `0.23.x`. Rn I can think of three possible ways to fix this:
> 
> 1. Update the `Pipfile` to have `pandas = ">=1.0.0"`
> 2. Remove declaring types in the `__init__` function (lines [52](https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/metric_snapshot_df.py#L52)-[56](https://github.com/AICoE/prometheus-api-client-python/blob/master/prometheus_api_client/metric_snapshot_df.py#L56))
> 3. Mirror the update in pandas that defines the `Dtype` and `Axes` types. i.e. replace this line:
> 
> ```
> from pandas._typing import Axes, Dtype
> ```
> 
> with this:
> 
> ```
> from typing import Collection
> from pandas.core.dtypes.dtypes import ExtensionDtype
> Axes = Collection
> Dtype = Union[str, np.dtype, "ExtensionDtype"]
> ```
> 
> Although, this method would break if pandas version was less than 0.20 (`pandas.core.dtypes.dtypes` didn't exist pre - 0.20)
> 
> WDYT? @4n4nd

The first suggested solution, to have pandas==1.0.0 works in my case. 
Thank you!

**Comment by 4n4nd** [comment] 2020-07-01 21:39
Can one of you folks update the Pipfile and the requirements.txt?

**Comment by chauhankaranraj** [comment] 2020-07-07 20:37
> Can one of you folks update the Pipfile and the requirements.txt?

Sure, I can update those. Unless @suppathak wants to do it?

**Comment by suppathak** [comment] 2020-07-08 02:56
> Can one of you folks update the Pipfile and the requirements.txt?

@chauhankaranraj @4n4nd Just updated the pipfile and requirement.txt file to have pandas = ">=1.0.0" and did PR

Thanks!

**Comment by 4n4nd** [comment] 2020-07-08 16:29
@suppathak Should we close this issue then?

**Comment by suppathak** [comment] 2020-07-08 16:36
> @suppathak Should we close this issue then?

If everything seems ok, we can close the issue!
Thanks :)

**Closed** 2020-07-08 16:37 UTC
Labels: bug, human_intervention_required
